### PR TITLE
fix(N-01) Remove TODOs and FixMes

### LINKED ISSUE #315: [Audit]: N-01 Unaddressed TODOs and FIXMEs
### What is the feature you would like to see?

Throughout the codebase, multiple instances of TODO and FIXME comments were identified:
 - line59 of ERC-20 extension metadata.rs
- line73 of ERC-20 extension enumerable.rs
- line11 of ERC-721 extension enumerable.rs
- line71 of ERC-721 extension mod.rs
 - line486 of ERC-721 extension mod.rs
 - line665 of ERC-721 extension mod.rs
 
 During development, having well-described TODO or FIXME comments will make the process of tracking and resolving them easier. Without this information, these comments might age and important information for the security of the system might be forgotten by the time it is released to production. As such, consider removing all instances of TODO or FIXME comments and instead tracking them in the issues backlog. Alternatively, consider linking each inline TODO or FIXME to a corresponding backlog issue.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines

### PR DESCRIPTION
**Pull request by ggonzalez94**
Resolves #315 

I'm leaving comments on things that might need some discussion

### CODE REVIEW

File: contracts/src/token/erc20/extensions/metadata.rs [hunk 1]
```diff
@@ -56,9 +56,6 @@ pub trait IErc20Metadata {
     fn decimals(&self) -> u8;
 }
 
-// FIXME: Apply multi-level inheritance to export Metadata's functions.
-// With the current version of SDK it is not possible.
-// See https://github.com/OffchainLabs/stylus-sdk-rs/pull/120
```
Comment (ggonzalez94) [inline contracts/src/token/erc20/extensions/metadata.rs:61]: We know multi-level inheritance is not the direction the SDK is going, and we found away around this that I think is acceptable, so I'm ok removing this without creating an issue

File: contracts/src/token/erc20/extensions/metadata.rs [hunk 2]
```diff
@@ -70,9 +67,6 @@ impl IErc20Metadata for Erc20Metadata {
     }
 
     fn decimals(&self) -> u8 {
-        // TODO: Use `U8` an avoid the conversion once
-        // https://github.com/OffchainLabs/stylus-sdk-rs/issues/117
-        // gets resolved.
```
Comment (ggonzalez94) [inline contracts/src/token/erc20/extensions/metadata.rs:75]: This was fixed, so we could change it, but do we actually want this?
- Since this is a view function and not intended to be put in storage, don't see a compelling reason to do so.
- It would involve removing the constant for `DEFAULT_DECIMALS` or converting in place to U8

File: contracts/src/token/erc721/extensions/enumerable.rs [hunk 3]
```diff
@@ -8,7 +8,6 @@
 //! [`super::super::Erc721::balance_of`] logic, such as `Erc721Consecutive`,
 //! interfere with enumerability and should not be used together with
 //! [`Erc721Enumerable`].
-// TODO: Add link for `Erc721Consecutive` to module docs.
```
Comment (ggonzalez94) [inline contracts/src/token/erc721/extensions/enumerable.rs:11]: I think we already did this right?

File: contracts/src/token/erc721/mod.rs [hunk 4]
```diff
@@ -483,8 +483,6 @@ impl IErc721 for Erc721 {
         to: Address,
         token_id: U256,
     ) -> Result<(), Error> {
-        // TODO: Once the SDK supports the conversion,
-        // use alloy_primitives::bytes!("") here.
```
Comment (ggonzalez94) [inline contracts/src/token/erc721/mod.rs:487]: Is it actually significantly better that it's worth tracking? I think the way it is today is probably ok, but happy to hear thoughts if I'm missing something(e.g. gas saving)

File: contracts/src/token/erc721/mod.rs [hunk 5]
```diff
@@ -662,9 +660,6 @@ impl Erc721 {
     /// * `&mut self` - Write access to the contract's state.
     /// * `account` - Account to increase balance.
     /// * `value` - The number of tokens to increase balance.
-    // TODO: Right now this function is pointless since it is not used.
-    // But once we will be able to override internal functions,
-    // it will make a difference.
```
Comment (ggonzalez94) [inline contracts/src/token/erc721/mod.rs:667]: This is probably the one that needs more discussion, but:
A) Internal function overriding is not very "rusty", so probably won't happen?
B) It is still useful for people writing extensions and being able to call this right? I think that's actually the way it is designed to work in Solidity

File: contracts/src/token/erc721/extensions/enumerable.rs [hunk 6]
```diff
@@ -68,8 +67,6 @@ pub trait IErc721Enumerable {
     /// implementation.
     type Error: Into<alloc::vec::Vec<u8>>;
 
-    // TODO: fn supports_interface (#33)
-
```
Comment (ggonzalez94) [inline contracts/src/token/erc721/extensions/enumerable.rs:72]: Should be solved once we merge ERC-165, so no need to track it AFAIK

File: contracts/src/token/erc721/mod.rs (hunk 5 above)
Comment (bidzyyys) [reply contracts/src/token/erc721/mod.rs:667]: A) 💯 
B) I cannot see big value in this function as it does not provide anything special but an additional "setter". IMHO it is fine to remove this fn.

File: contracts/src/token/erc20/extensions/metadata.rs (hunk 1 above)
Comment (bidzyyys) [reply contracts/src/token/erc20/extensions/metadata.rs:61]: IMHO yes.

File: contracts/src/token/erc20/extensions/metadata.rs (hunk 2 above)
Comment (bidzyyys) [reply contracts/src/token/erc20/extensions/metadata.rs:75]: Do not see any valid reason tbh.

File: contracts/src/token/erc721/mod.rs (hunk 4 above)
Comment (bidzyyys) [reply contracts/src/token/erc721/mod.rs:487]: I do not think so.

**Review by bidzyyys — APPROVED** [review]

File: contracts/src/token/erc721/mod.rs (hunk 4 above)
Comment (qalisander) [reply contracts/src/token/erc721/mod.rs:487]: Not significantly better. I suspect would be zero difference in gas:) Do we have a zero todo's policy in code?:D

File: contracts/src/token/erc721/mod.rs (hunk 5 above)
Comment (qalisander) [reply contracts/src/token/erc721/mod.rs:667]: Basically it is used at consecutive now. In solidity it is impossible to access private fields from child contracts. At stylus it can work, but I feel it's a bad development practice.
As I see the function is just for convenience.
We can remove misleading `TODO`.

File: contracts/src/token/erc721/mod.rs (hunk 4 above)
Comment (ggonzalez94) [reply contracts/src/token/erc721/mod.rs:487]: No, I don't think we should aim for that. Just maybe before each audit we make sure to clean things and move outstanding TODOs to issues? Since we know otherwise they will become findings in the report
