### PR TITLE
ref: small changes + warning fixes

### LINKED ISSUE #721: [Feature]: Update README stating to update `export-abi` feature to include `opezeppelin-stylus/export-abi`
### What is the feature you would like to see?

```rust
export-abi = ["stylus-sdk/export-abi"]
```
should be updated to:
```rust
export-abi = ["stylus-sdk/export-abi", "opezeppelin-stylus/export-abi"]
```

### Contribution Guidelines

- [x] I agree to follow this project's Contribution Guidelines

### PR DESCRIPTION
**Pull request by 0xNeshi**
Resolves #721 

#### PR Checklist

- [x] Tests
- [x] Documentation
- [x] Changelog

### CODE REVIEW

File: examples/erc1155-supply/src/lib.rs [hunk 1]
```diff
@@ -105,20 +108,20 @@ impl IErc1155Burnable for Erc1155Example {
...
     fn burn(
         &mut self,
-        from: Address,
-        id: U256,
+        account: Address,
+        token_id: U256,
         value: U256,
     ) -> Result<(), Self::Error> {
-        self.erc1155_supply._burn(from, id, value)
+        self.erc1155_supply._burn(account, token_id, value)
```
Comment (0xNeshi) [inline examples/erc1155-supply/src/lib.rs:115]: Align with [IErc1155Burnable](https://github.com/OpenZeppelin/rust-contracts-stylus/blob/e15e5796890af819032f81aca2f7a0288642a450/contracts/src/token/erc1155/extensions/burnable.rs#L37) naming

File: contracts/src/utils/structs/checkpoints/mod.rs [hunk 2]
```diff
@@ -336,7 +336,7 @@ impl<S: Size> Trace<S> {
     /// # Panics
     ///
     /// * If `pos` exceeds [`Self::length`].
-    fn _index(&self, pos: U256) -> StorageGuard<Checkpoint<S>> {
+    fn _index(&self, pos: U256) -> StorageGuard<'_, Checkpoint<S>> {
```
Comment (0xNeshi) [inline contracts/src/utils/structs/checkpoints/mod.rs:339]: Address https://github.com/OpenZeppelin/rust-contracts-stylus/actions/runs/15932476670/job/44944683046?pr=724#step:4:56

File: lib/crypto/src/poseidon2/mod.rs [hunk 3]
```diff
@@ -27,8 +27,10 @@ use crate::{field::prime::PrimeField, poseidon2::params::PoseidonParams};
 /// Determines whether poseidon sponge in absorbing or squeezing state.
 /// In squeezing state, sponge can only squeeze elements.
 #[derive(Clone, Copy, Debug, PartialEq)]
-enum Mode {
+pub enum Mode {
+    /// Sponge is in absorbing state.
     Absorbing,
+    /// Sponge is in squeezing state.
     Squeezing,
 }
```
Comment (0xNeshi) [inline lib/crypto/src/poseidon2/mod.rs:35]: Address https://github.com/OpenZeppelin/rust-contracts-stylus/actions/runs/15932476670/job/44944683046?pr=724#step:4:56

File: contracts/src/token/erc20/extensions/flash_mint.rs [hunk 4]
```diff
@@ -356,6 +356,15 @@ impl Erc20FlashMint {
     }
 }
 
+// TODO: implement `IErc165` once `IErc3156FlashLender` is implemented for
```
Comment (bidzyyys) [inline contracts/src/token/erc20/extensions/flash_mint.rs:359]: Create GH Issue and add it to M3 please.

**Review by bidzyyys — APPROVED** [review]

File: contracts/src/utils/structs/checkpoints/mod.rs (hunk 2 above)
Comment (qalisander) [inline contracts/src/utils/structs/checkpoints/mod.rs:339]: It seems like a false positive for me (if I'm not mistaken)

File: contracts/src/token/erc20/extensions/flash_mint.rs (hunk 4 above)
Comment (bidzyyys) [reply contracts/src/token/erc20/extensions/flash_mint.rs:359]: GH Added: https://github.com/OpenZeppelin/rust-contracts-stylus/issues/727

File: contracts/src/utils/structs/checkpoints/mod.rs (hunk 2 above)
Comment (0xNeshi) [reply contracts/src/utils/structs/checkpoints/mod.rs:339]: It doesn't seem so, though it's debatable how useful this is. The Rust compiler is warning us to be explicit about `StorageGuard` having different lifetime from `&self`.
