### PR TITLE
fix(audit): L-07, N-08: Custom Selectors in Trait With interface_id Allows Unreachable Patterns

### LINKED ISSUE #697: [Fix(Audit)]: L-07: Custom Selectors in Trait With  interface_id Allows Unreachable Patterns
### What is the feature you would like to see?

The  #[interface_id]  attribute allows custom selectors to be added to function signatures
in traits using the  #[selector]  attribute, reproducing the functionality that exists for
functions within  #[public]  implementation blocks provided by the Stylus SDK. Code that
includes functions with identical selectors in  #[public]  blocks produces a unreachable
pattern error, but this is not enforced in traits with the  #[interface_id] . It is then possible
to create traits with the  #[interface_id]  attribute that can never be implemented. To
preserve expected programming invariants and minimize developer errors, consider
disallowing the ability to create traits that have two identical function selectors.

### Contribution Guidelines

- [x] I agree to follow this project's Contribution Guidelines

### PR DESCRIPTION
**Pull request by 0xNeshi**
Resolves #697 

#### PR Checklist

- [x] Tests
- [x] Documentation
- [x] Changelog

### CODE REVIEW

File: contracts-proc/src/lib.rs [hunk 1]
```diff
@@ -18,21 +18,27 @@ macro_rules! error {
 
 mod interface_id;
 
-/// Computes the interface id as an associated constant `INTERFACE_ID` for the
-/// trait that describes contract's abi.
+/// Automatically computes the ERC-165 interface ID for a trait.
 ///
-/// Selector collision should be handled with
-/// macro `#[selector(name = "actualSolidityMethodName")]` on top of the method.
+/// Adds an `interface_id` associated function to your trait by XORing all
```
Comment (0xNeshi) [inline contracts-proc/src/lib.rs]:
```suggestion
/// Adds an `interface_id` associated function to your trait by XOR-ing all
```
