### PR TITLE
ref: Add/Sub Assignment Operations + e2e-tests.sh

### LINKED ISSUE #443: [Feature]: Make E2E Target Names Easier to Use (i.e. Make _e2e-tests.sh_ Script Easier to Use)
### What is the feature you would like to see?

E.g. currently there's no way to run only `safe-erc20-example` e2e tests without modifying the _e2e-tests.sh_ script. 
This is because we run our e2e tests from the workspace, which looks at _file names_ to filter out specific tests to run. 

Let's say you wanted to run them - you'd probably write something like:

```bash
./scripts/e2e-tests.sh safe-erc20*
```

This will error out with the following log:

```bash
error: no test target matches pattern `safe-erc20*`.
Available test targets:
    access_control
    ecdsa
    erc1155
    erc1155-metadata-uri
    erc20
    erc20permit
    erc721-consecutive
    erc721
    erc721
    ownable
    ownable_two_step
    address_with_no_code
    erc20
    erc20_that_always_returns_false
    erc20_that_does_not_return
    usdt_approval_behavior
    vesting-wallet
```

A couple of problems are immediately noticeable:
1. No target name indicates a relation to `SafeErc20`.
1. There are duplicate target names.
1. There seem to be missing certain e2e tests.

This may not be necessarily a problem for us who are intimately acquainted with our code base, but it will be a problem for any new contributor, both external, and potentially internal ones.

_I propose we make it even easier and clearer how to run e2e tests from the command line using one of the below approaches:_

1. **Rename each e2e test file to start with its directory name.**
    Pros:
    - No change necessary to _e2e-tests.sh_ script.
    - Filtering tests (e.g.  `safe-erc20*` - note the asterisk) becomes easier.
    Cons:
    - Long and repetitive file names.
2. **~~Update _e2e-tests.sh_ to run tests withing specific _packages_.~~**
    ~~Pros:~~
    ~~- File names remain unchanged.~~
    ~~Cons:~~
    ~~- Writing a wrong package name does not list valid packages.~~
    ```bash
    ~$ ./scripts/e2e-tests.sh non-existent-package
        Finished `release` profile [optimized] target(s) in 0.12s
    error: cannot specify features for packages outside of workspace
    ```
    ~~- Need to declare `std` feature in all examples.~~
    
I'm in favor of option 1) just because when a wrong target name is typed, the error log contains all valid targets.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines

### LINKED ISSUE #444: [Feature]: Update _e2e-tests.sh_ Script to Allow Targeting Specific Test Cases Within Test Files
### What is the feature you would like to see?

It is possible to update _e2e-tests.sh_ so that we're able to use it in the following ways:

```bash
# run every test
./scripts/e2e-tests.sh
# run only tests in files named 'erc721'
./scripts/e2e-tests.sh erc721
# run every test file starting with 'erc721' (erc721)
./scripts/e2e-tests.sh erc721*
# run only test cases that contain 'support_interface' in their name from within erc721 test files
./scripts/e2e-tests.sh erc721 -- support_interface
# run all tests, and pass custom flags/params to `cargo test`
./scripts/e2e-tests.sh * --nocapture
```

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines

### LINKED ISSUE #445: [Feature]: Shorten All Relevant Add/Sub Assignment Operations in Every Contract
### What is the feature you would like to see?

The `AddAssignUnchecked` and `SubAssignUnchecked` traits are implemented for `StorageUint` (see [source](https://github.com/OpenZeppelin/rust-contracts-stylus/blob/9192c1849680f0c0f60822ac288b172a8b276c89/contracts/src/utils/math/storage.rs)).

This makes it possible to shorten integer state assignments from:

```rust
let total_supply_all = self._total_supply_all.get() - total_burn_value;
self._total_supply_all.set(total_supply_all);
```

To a one-liner:

```rust
self._total_supply_all.sub_assign_unchecked(total_burn_value);
```

We should update all similar state updates in all contracts.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines

### PR DESCRIPTION
**Pull request by 0xNeshi**
Resolves #445, Resolves #444 

#### PR Checklist

- [x] Tests
- [x] Documentation
- [x] Changelog

### CODE REVIEW

File: contracts/src/utils/nonces.rs [hunk 1]
```diff
@@ -60,13 +60,17 @@ impl Nonces {
...
-    /// method to return `None`.
+    /// the function will experience **undefined behavior**, if the nonce for
+    /// the given `owner` has reached the maximum value representable by `U256`.
+    /// Extreme caution should be taken to ensure overflow cannot occur.
     pub fn use_nonce(&mut self, owner: Address) -> U256 {
         let nonce = self._nonces.get(owner);
+
+        // For each account, the nonce has an initial value of 0, can only be
+        // incremented by one, and cannot be decremented or reset. This
+        // guarantees that the nonce never overflows.
```
Comment (0xNeshi) [inline contracts/src/utils/nonces.rs:73]: Add comment from [Solidity version](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/c3b3ae7e82c6694c1c5c12e6eb832db55ef1e7fd/contracts/utils/Nonces.sol#L29)

File: scripts/e2e-tests.sh [hunk 2]
```diff
@@ -1,14 +1,18 @@
...
+# Set RPC_URL environment variable
 export RPC_URL=http://localhost:8547
 
-cargo test --features std,e2e --test "$TEST_ARG"
+# Run tests based on arguments
+if [[ $# -eq 0 ]]; then
+    cargo test --features std,e2e --test "*"
+else
+    cargo test --features std,e2e "$@"
+fi
```
Comment (0xNeshi) [inline scripts/e2e-tests.sh:16]: The script can now be called in the following ways:

- if no arguments are passed, the behavior is the same as before
- otherwise, pass whatever arguments are present to `cargo test` directly

We can now easily filter for even unit tests with this script. 

This should cover most of our testing needs.

NOTE: feel free to suggest or add any additional feature you think might be useful.

Comment (0xNeshi) [reply scripts/e2e-tests.sh:16]: An other option is to omit the if-statement, and just call `cargo test --features std,e2e "$@"`, passing whatever arguments to the command. In our e2e workflow, we'd then call the script like `./scripts/e2e-tests.sh --test "*"`.

At this point it's really a matter of taste

**Review by bidzyyys — COMMENTED** [review]
I believe we can apply `#[allow(clippy::used_underscore_binding)]` for the whole contracts library

File: CHANGELOG.md [hunk 3]
```diff
@@ -5,6 +5,25 @@ All notable changes to this project will be documented in this file.
...
 
+## [Unreleased]
+
+### Added
+
+- 
+
+### Changed
+
+- Refactor how `AddAssignUnchecked` and `SubAssignUnchecked` are used in `Erc20`, `Erc721`, and `Erc721Consecutive`. #467
```
Comment (bidzyyys) [inline CHANGELOG.md:16]:
```suggestion
- Refactor how `AddAssignUnchecked` and `SubAssignUnchecked` traits are used in `Erc20`, `Erc721`, and `Erc721Consecutive`. #467
```

File: CHANGELOG.md [hunk 4]
```diff
@@ -5,6 +5,25 @@ All notable changes to this project will be documented in this file.
...
+- Refactor `Nonces`. #467
```
Comment (bidzyyys) [inline CHANGELOG.md:17]: IMHO if anything in API has changed than we should mention this change. If not, no need.

File: contracts/src/utils/nonces.rs [hunk 5]
```diff
@@ -60,13 +61,19 @@ impl Nonces {
     /// * `&mut self` - Write access to the contract's state.
     /// * `owner` - The address for which to consume the nonce.
     ///
-    /// # Panics
+    /// # Safety
     ///
-    /// This function will panic if the nonce for the given `owner` has reached
-    /// the maximum value representable by `U256`, causing the `checked_add`
-    /// method to return `None`.
+    /// the function will experience [undefined behavior], if the nonce for
```
Comment (bidzyyys) [inline contracts/src/utils/nonces.rs:66]:
```suggestion
    /// This function will experience [undefined behavior], if the nonce for
```

File: contracts/src/utils/nonces.rs [hunk 6]
```diff
@@ -60,13 +61,19 @@ impl Nonces {
...
+    /// the given `owner` has reached the maximum value representable by `U256`.
+    /// Extreme caution should be taken to ensure overflow cannot occur.
+    ///
+    /// [undefined behavior]: https://doc.rust-lang.org/reference/behavior-considered-undefined.html
     pub fn use_nonce(&mut self, owner: Address) -> U256 {
         let nonce = self._nonces.get(owner);
+
+        // For each account, the nonce has an initial value of 0, can only be
```
Comment (bidzyyys) [inline contracts/src/utils/nonces.rs:74]:
```suggestion
        // For each account, the nonce has an initial value of `U256::ZERO`, can only be
```

File: contracts/src/utils/nonces.rs [hunk 7]
```diff
@@ -83,34 +90,32 @@ impl Nonces {
     /// * `owner` - The address for which to consume the nonce.
     /// * `nonce` - The nonce to consume.
     ///
-    /// # Panics
+    /// # Safety
     ///
-    /// This function will panic if the nonce for the given `owner` has reached
-    /// the maximum value representable by `U256`, causing the `checked_add`
-    /// method to return `None`.
+    /// the function will experience [undefined behavior], if the nonce for
```
Comment (bidzyyys) [inline contracts/src/utils/nonces.rs:95]:
```suggestion
    /// This function will experience [undefined behavior], if the nonce for
```

File: contracts/src/utils/nonces.rs [hunk 8]
```diff
@@ -60,13 +61,19 @@ impl Nonces {
...
+    /// [undefined behavior]: https://doc.rust-lang.org/reference/behavior-considered-undefined.html
     pub fn use_nonce(&mut self, owner: Address) -> U256 {
         let nonce = self._nonces.get(owner);
+
+        // For each account, the nonce has an initial value of 0, can only be
+        // incremented by one, and cannot be decremented or reset. This
+        // guarantees that the nonce never overflows.
         self._nonces
             .setter(owner)
             .set(unsafe { nonce.checked_add(ONE).unwrap_unchecked() });
```
Comment (bidzyyys) [inline contracts/src/utils/nonces.rs:79]: Tbh I do not like code where we use `unsafe` in our contracts. Is it possible to apply panicking operation before the setter?

**Review by bidzyyys — COMMENTED** [review]
Left some comments, good job @0xNeshi

File: CHANGELOG.md (hunk 4 above)
Comment (0xNeshi) [inline CHANGELOG.md:17]:
```suggestion
```

File: contracts/src/access/control.rs [hunk 9]
```diff
@@ -119,6 +119,7 @@ pub struct RoleData {
 #[storage]
 pub struct AccessControl {
     /// Role identifier -> Role information.
+    #[allow(clippy::used_underscore_binding)]
```
Comment (0xNeshi) [inline contracts/src/access/control.rs:122]: In response to :
> I believe we can apply `#[allow(clippy::used_underscore_binding)]` for the whole contracts library

We would then not get warnings for:

```rust
let _x = 1u32;
let y = _x + 1; // should be a warning
```

File: contracts/src/utils/nonces.rs (hunk 8 above)
Comment (0xNeshi) [reply contracts/src/utils/nonces.rs:79]: I don't really understand how this "guarantees that the nonce never overflows", but that's what's in the Solidity version.

How bad performance-wise can it be if we _did_ check for overflows here?

Comment (bidzyyys) [reply contracts/src/utils/nonces.rs:79]: I believe we should have panic here to make it obvious that it may fail, like:
```rust
let updated_nonce = nonce.checked_add(ONE).expect("...");
 self._nonces
            .setter(owner)
            .set(updated_nonce);
```

Comment (bidzyyys) [reply contracts/src/utils/nonces.rs:79]: And then we need to have `# Panics` sections in Rust docs for proper fns.

File: contracts/src/access/control.rs (hunk 9 above)
Comment (bidzyyys) [reply contracts/src/access/control.rs:122]: Fair enough. I am ok with leaving as it is.

**Review by bidzyyys — COMMENTED** [review]
Almost ready to merge!

File: contracts/src/access/control.rs (hunk 9 above)
Comment (0xNeshi) [reply contracts/src/access/control.rs:122]: It would be useful to have an attribute similar to [`[serde(rename = ...)]`](https://serde.rs/field-attrs.html#rename), so we could use Rust conventions for naming fields, and just rename those fields when building the contract :thinking:

Comment (0xNeshi) [reply contracts/src/access/control.rs:122]: Actually, are we really required to use the same names as in Solidity?

It is a Solidity convention to prefix private state fields with an underscore `_`, but this is not the case in Rust. 

Why can't we just omit the underscore?

Comment (0xNeshi) [reply contracts/src/access/control.rs:122]: @bidzyyys @qalisander

File: contracts/src/utils/nonces.rs (hunk 8 above)
Comment (0xNeshi) [reply contracts/src/utils/nonces.rs:79]: @bidzyyys @qalisander I think this was mentioned before, but it would be useful to have "checked" add/sub assign versions in [math/storage.rs](https://github.com/OpenZeppelin/rust-contracts-stylus/blob/59c1ead477e969e0d85b27ac8784c760acbb8ca0/contracts/src/utils/math/storage.rs):

```rust
trait AddAssignChecked
trait SubAssignChecked
```

File: contracts/src/access/control.rs (hunk 9 above)
Comment (bidzyyys) [reply contracts/src/access/control.rs:122]: @0xNeshi this is the corresponding issue #386 that we have. Tbh I do not like either as it is against Rust attitude. Right now I would merge as it is and then focus on renaming based on our common agreement.

File: contracts/src/finance/vesting_wallet.rs [hunk 10]
```diff
@@ -107,12 +107,16 @@ pub struct VestingWallet {
     /// [`Ownable`] contract.
     pub ownable: Ownable,
     /// Amount of Ether already released.
+    #[allow(clippy::used_underscore_binding)]
```
Comment (bidzyyys) [inline contracts/src/finance/vesting_wallet.rs:110]: I can see some inconsistency in attributes' naming, e.g. `ownable` & `_released`. We should fix it with #386.

File: scripts/e2e-tests.sh (hunk 2 above)
Comment (bidzyyys) [reply scripts/e2e-tests.sh:16]: Let's leave right now the current behaviour.

**Review by bidzyyys — APPROVED** [review]
LGTM!

File: contracts/src/utils/nonces.rs (hunk 8 above)
Comment (bidzyyys) [reply contracts/src/utils/nonces.rs]: @0xNeshi yeah, having "safe" (`Checked`) operation would be great. If you want to include those traits in this PR go ahead; If not feel free to add an issue to this milestone.

File: scripts/e2e-tests.sh [hunk 11]
```diff
@@ -1,14 +1,16 @@
 #!/bin/bash
 set -e
 
-TEST_ARG="${1:-*}"
-
-MYDIR=$(realpath "$(dirname "$0")")
-cd "$MYDIR"
-cd ..
+# Navigate to project root
+cd "$(dirname "$(realpath "$0")")/.."
```
Comment (qalisander) [inline scripts/e2e-tests.sh:5]: Consider that reduction of code lines, doesn't reduce code complexity.
After all we could feed all code as a single line to compiler and he will be fine.

p.s. If you think that new changes are better lets keep them

File: examples/erc20/src/lib.rs [hunk 12]
```diff
@@ -110,6 +110,10 @@ impl Erc20Example {
             || Erc20Metadata::supports_interface(interface_id)
     }
 
+    /// WARNING: These functions are intended for **testing purposes** only. In
```
Comment (qalisander) [inline examples/erc20/src/lib.rs:113]: ++

File: contracts/src/utils/math/storage.rs [hunk 13]
```diff
@@ -8,11 +8,13 @@ pub(crate) trait AddAssignUnchecked<T> {
...
-impl<const B: usize, const L: usize> AddAssignUnchecked<Uint<B, L>>
+impl<T, const B: usize, const L: usize> AddAssignUnchecked<T>
     for StorageUint<B, L>
+where
+    Uint<B, L>: UintTryFrom<T>,
 {
-    fn add_assign_unchecked(&mut self, rhs: Uint<B, L>) {
-        let new_balance = self.get() + rhs;
+    fn add_assign_unchecked(&mut self, rhs: T) {
+        let new_balance = self.get() + Uint::<B, L>::from(rhs);
```
Comment (qalisander) [inline contracts/src/utils/math/storage.rs:17]: This refactoring looks smart.
But initial reason why we are rarely using `Uint::<_,_>::from(..)` method, that it performs conversion in runtime.

In the following example a conversion is done at compile time, with the help of `uint!` macro.

```
self._balances.setter(from).sub_assign_unchecked(uint!(1_U256))
```

Also `Uint::<B, L>::from` has actual conversion code beneath with size checks, and we have `add_unsigned_unchecked` function name

File: contracts/src/access/control.rs (hunk 9 above)
Comment (qalisander) [reply contracts/src/access/control.rs:122]: Don't like `_*` either

**Review by qalisander — COMMENTED** [review]
Good job!

File: contracts/src/access/control.rs (hunk 9 above)
Comment (0xNeshi) [reply contracts/src/access/control.rs:122]: Seems the agreement is there :smile: 
Nevertheless, I'd prefer this be done as part of a separate PR linked to the [issue you mentioned](https://github.com/OpenZeppelin/rust-contracts-stylus/issues/386)

File: contracts/src/utils/math/storage.rs (hunk 13 above)
Comment (0xNeshi) [reply contracts/src/utils/math/storage.rs:17]: This is actually a very good catch!
I'll revert this, and try to think of a way to keep this generic, but won't spend too much time on it.

File: scripts/e2e-tests.sh (hunk 11 above)
Comment (0xNeshi) [reply scripts/e2e-tests.sh:5]: To me it's the same, as the dirname+realpath combo is (un)clear enough.

Though now that I think about it, wouldn't it be enough to just do `cd ..`? :thinking:

File: contracts/src/utils/nonces.rs (hunk 1 above)
Comment (0xNeshi) [reply contracts/src/utils/nonces.rs]: Removed

File: scripts/e2e-tests.sh (hunk 2 above)
Comment (0xNeshi) [reply scripts/e2e-tests.sh:16]: Basically, it lets you call this script as if you were to call `cargo test`, meaning it enables you to do all the funky filtering stuff

File: contracts/src/utils/nonces.rs (hunk 8 above)
Comment (0xNeshi) [reply contracts/src/utils/nonces.rs]: I'll add a separate issue, as there are many contracts where the change could be applied

File: contracts/src/utils/math/storage.rs (hunk 13 above)
Comment (0xNeshi) [reply contracts/src/utils/math/storage.rs:17]: Wait, does this mean that `uint!` is more performant than `U256::from`?

File: contracts/src/utils/nonces.rs (hunk 8 above)
Comment (0xNeshi) [reply contracts/src/utils/nonces.rs]: Here's the issue https://github.com/OpenZeppelin/rust-contracts-stylus/issues/469

File: scripts/e2e-tests.sh (hunk 2 above)
Comment (0xNeshi) [reply scripts/e2e-tests.sh:13]: All of these are now supported

```bash
# run all tests (appends `--test "*"` as before)
./scripts/e2e-tests.sh
# pass arguments to `cargo test`
./scripts/e2e-tests.sh --test erc721
./scripts/e2e-tests.sh --no-run
# pass arguments both to `cargo test` and to test binary
./scripts/e2e-tests.sh --test erc721 -- support_interface
./scripts/e2e-tests.sh erc721 --no-run -- --nocapture
```

Comment (qalisander) [reply scripts/e2e-tests.sh:13]: I see.
But in this case it is impossible to invoke the command like `./scripts/e2e-tests.sh erc721 error_when_minting_token_id_twice`

If you would change it like this:
```
if [[ $# -eq 0 ]]; then
    cargo test --features std,e2e --test "*"
else
    cargo test --features std,e2e --test "$@"
fi
```
It can work.

Comment (qalisander) [reply scripts/e2e-tests.sh:13]: And we should spell it like `./scripts/e2e-tests.sh --test erc721 error_when_minting_token_id_twice`

Comment (qalisander) [reply scripts/e2e-tests.sh:13]: But actually what I like very much in your approach, is that if we spell `./scripts/e2e-tests.sh --help` it will print docs for cargo sub commands. So no need to bother ourselves with script's documentation

File: scripts/e2e-tests.sh (hunk 11 above)
Comment (qalisander) [reply scripts/e2e-tests.sh]: I see it was necessary before:D or just a good tone of writing repo wide scripts. Step to root directory first

File: contracts/src/utils/math/storage.rs (hunk 13 above)
Comment (qalisander) [reply contracts/src/utils/math/storage.rs]: Instead of adding `ONE`, we first "create `ONE` from integer checking that integer is not bigger. If it is bigger then panic, if not" add ONE to the value

Comment (qalisander) [reply contracts/src/utils/math/storage.rs]: Ofc it won't affect performance dramatically and we wont notice it probably. But I don't see much point of that kind of refactoring. We don't win much in code simplicity.

File: scripts/e2e-tests.sh (hunk 2 above)
Comment (0xNeshi) [reply scripts/e2e-tests.sh:13]: The current implementation is the simplest one, with the most straightforward way to use.

Updating the script to support invocations like:
```bash
./scripts/e2e-tests.sh erc721 error_when_minting_token_id_twice
```
Would make it very complex if we also wanted to support passing other valid args/flags to `cargo test`, or to the test binary.

> But actually what I like very much in your approach, is that if we spell ./scripts/e2e-tests.sh --help it will print docs for cargo sub commands. So no need to bother ourselves with script's documentation

Can you clarify the last sentence?

File: scripts/e2e-tests.sh (hunk 11 above)
Comment (qalisander) [reply scripts/e2e-tests.sh]: Lets use then this construct in other scripts
```
# Move to project root
cd "$(dirname "$(realpath "$0")")/.."
```

File: scripts/e2e-tests.sh (hunk 2 above)
Comment (qalisander) [reply scripts/e2e-tests.sh:13]: Let's keep you changes

File: scripts/e2e-tests.sh (hunk 11 above)
Comment (0xNeshi) [reply scripts/e2e-tests.sh]: My bad, it is actually better to ensure we're in the project root :sweat_smile: 

I don't mind reverting this to the way it was before, to me it's the same. Will do so.

File: contracts/src/utils/math/storage.rs (hunk 13 above)
Comment (0xNeshi) [reply contracts/src/utils/math/storage.rs]: You're right, reverted the change https://github.com/OpenZeppelin/rust-contracts-stylus/pull/467/commits/c3a1599b2397eda8aa71bf29f2f671594c66e7d0

File: scripts/e2e-tests.sh (hunk 2 above)
Comment (qalisander) [reply scripts/e2e-tests.sh:16]: > Can you clarify the last sentence?
I mean, that we can print valid documentation for `e2e-test.sh` script, since we're just forwarding arguments to `cargo test` like:
```./scripts/e2e-tests.sh --help```

Comment (0xNeshi) [reply scripts/e2e-tests.sh:16]: Does the script then have your blessing? :smile:

**Review by qalisander — APPROVED** [review]
LGTM

**Review by bidzyyys — APPROVED** [review]
LGTM! 🚀
