### PR TITLE
fix(L-04): Public Exposure of pause and unpause Functions

### LINKED ISSUE #314: [Audit]: L-04 Public Exposure of pause and unpause Functions
### What is the feature you would like to see?

The   contract exposes the pause and unpause functions as part of a public implementation block. This design automatically makes these functions available
in any inheriting contract's public ABI, without any access control restrictions. In the Solidity version of the Pausable contract, the corresponding functions are marked as internal . This forces developers to explicitly declare external or public functions that interact with
pause and unpause , and ensures that proper access control measures are applied.
Consider placing the pause and unpause functions in a non-public implementation block, preventing their exposure via the ABI by default. This will enforce explicit access control, reducing the risk of unintended function access.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines

### PR DESCRIPTION
**Pull request by qalisander**
Methods `pause` and `unpause` are not exposed by default now.

Resolves #314

### CODE REVIEW

File: contracts/src/utils/pausable.rs [hunk 1]
```diff
@@ -9,6 +9,10 @@
 //!
 //! Note that they will not be pausable by simply including this module,
 //! only once the modifiers are put in place.
+//!
+//! Note that [`Pausable::pause`] and [`Pausable::unpause`] methods are not
+//! exposed by default.
+//! You should expose them manually in your contract's abi.
```
Comment (bidzyyys) [inline contracts/src/utils/pausable.rs:15]:
```suggestion
//! You should expose them manually in your contract.
```

File: examples/erc721/src/lib.rs [hunk 2]
```diff
@@ -151,4 +151,12 @@ impl Erc721Example {
 
         Ok(())
     }
+
+    pub fn pause(&mut self) -> Result<(), Error> {
```
Comment (bidzyyys) [inline examples/erc721/src/lib.rs:155]: `Error` is inconsistent with other functions.

File: examples/erc721/src/lib.rs [hunk 3]
```diff
@@ -151,4 +151,12 @@ impl Erc721Example {
...
+        self.pausable.pause()
+    }
+
+    pub fn unpause(&mut self) -> Result<(), Error> {
```
Comment (bidzyyys) [inline examples/erc721/src/lib.rs:159]: `Error` is inconsistent with other functions.

File: examples/erc20/src/lib.rs [hunk 4]
```diff
@@ -105,4 +105,12 @@ impl Erc20Example {
         self.pausable.when_not_paused()?;
         self.erc20.transfer_from(from, to, value).map_err(|e| e.into())
     }
+
+    pub fn pause(&mut self) -> Result<(), Error> {
+        self.pausable.pause()
+    }
+
+    pub fn unpause(&mut self) -> Result<(), Error> {
```
Comment (bidzyyys) [inline examples/erc20/src/lib.rs:113]: `Error` is inconsistent with other functions.

File: examples/erc20/src/lib.rs [hunk 5]
```diff
@@ -105,4 +105,12 @@ impl Erc20Example {
         self.pausable.when_not_paused()?;
         self.erc20.transfer_from(from, to, value).map_err(|e| e.into())
     }
+
+    pub fn pause(&mut self) -> Result<(), Error> {
```
Comment (bidzyyys) [inline examples/erc20/src/lib.rs:109]: `Error` is inconsistent with other functions.

**Review by bidzyyys — COMMENTED** [review]
Left some comments @qalisander

File: examples/erc721/src/lib.rs (hunk 2 above)
Comment (qalisander) [reply examples/erc721/src/lib.rs:155]: I think it is fine. One less conversion to `Vec<u8>` in code.
cc @ggonzalez94

File: contracts/src/utils/pausable.rs (hunk 1 above)
Comment (qalisander) [reply contracts/src/utils/pausable.rs:15]: Isn't previous way more clear for novice library user?
wdt @ggonzalez94 ?

File: contracts/src/utils/pausable.rs [hunk 6]
```diff
@@ -68,73 +72,75 @@ impl Pausable {
...
     /// # Errors
     ///
-    /// If the contract is in `Paused` state, then the error
+    /// If the contract is in the `Paused` state, then the error
     /// [`Error::EnforcedPause`] is returned.
-    pub fn pause(&mut self) -> Result<(), Error> {
-        self.when_not_paused()?;
-        self._paused.set(true);
-        evm::log(Paused { account: msg::sender() });
+    pub fn when_not_paused(&self) -> Result<(), Error> {
```
Comment (ggonzalez94) [inline contracts/src/utils/pausable.rs:86]: I know we already had this as part of the contract public abi, but do we want this? It seems like it would be better to move it and keep it internal to the contract.

File: contracts/src/utils/pausable.rs [hunk 7]
```diff
@@ -68,73 +72,75 @@ impl Pausable {
...
     ///
     /// # Errors
     ///
     /// If the contract is in `Unpaused` state, then the error
     /// [`Error::ExpectedPause`] is returned.
-    pub fn unpause(&mut self) -> Result<(), Error> {
-        self.when_paused()?;
-        self._paused.set(false);
-        evm::log(Unpaused { account: msg::sender() });
+    pub fn when_paused(&self) -> Result<(), Error> {
```
Comment (ggonzalez94) [inline contracts/src/utils/pausable.rs:104]: Same question as above.
I know we already had this as part of the contract public abi, but do we want this? It seems like it would be better to move it and keep it internal to the contract.

**Review by ggonzalez94 — COMMENTED** [review]
Looks good overall! Left one small comment and a questions that came to my mind as I was reviewing about the visibility of the "modifiers"

File: contracts/src/utils/pausable.rs (hunk 1 above)
Comment (ggonzalez94) [reply contracts/src/utils/pausable.rs:15]: I also prefer to keep the explicit word abi.

File: examples/erc721/src/lib.rs (hunk 2 above)
Comment (ggonzalez94) [reply examples/erc721/src/lib.rs:155]: I don't like `Vec<u8>`, but for consistency inside this example I would stick with it. It looks rare and might be confusing if inside the same file there are some functions that return `Result<(), Error> ` and others that return `Result<(), Vec<u8>>`even if they are equivalent.
We can do a refactor of all return types later as part of this [issue](https://github.com/OpenZeppelin/rust-contracts-stylus/issues/282). WDYT?

Comment (bidzyyys) [reply examples/erc721/src/lib.rs:155]: I agree on refactoring later.

File: contracts/src/utils/pausable.rs (hunk 7 above)
Comment (bidzyyys) [reply contracts/src/utils/pausable.rs:104]: It's a good question. IMHO modifiers do not need to be callable so I would move them from `#[public]` impl block to the second one.

File: contracts/src/utils/pausable.rs [hunk 8]
```diff
@@ -68,73 +72,75 @@ impl Pausable {
         self._paused.get()
     }
 
-    /// Triggers `Paused` state.
+    /// Modifier to make a function callable only when the contract is NOT
```
[the remark this answers is not in the document]
Comment (qalisander) [reply contracts/src/utils/pausable.rs:75]: this should be better: "Returns error when the contract is NOT paused."

File: contracts/src/utils/pausable.rs (hunk 7 above)
Comment (qalisander) [reply contracts/src/utils/pausable.rs]: Made them private and updated tests

**Review by ggonzalez94 — APPROVED** [review]
Much cleaner interface, love it.

**Review by bidzyyys — APPROVED** [review]
LGTM!
