### PR TITLE
fix: reference-types error on nightly version

### LINKED ISSUE #294: ref: add rust-toolchain.toml
### What is the feature you would like to see?

- [x] add `rust-toolchain.toml` file and specify the right Rust version (`nightly-2024-01-01`).
- [ ] remove all occurences of Rust version spec in scripts & CI

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines

### LINKED ISSUE #374: [Bug]: Impossible to deploy contract on the latest nightly
### What happened?

Currently nightly versions higher then `nightly-2024-07-25` doesn't work.

image

### platform

- [X] linux
- [ ] windows
- [X] macos

### Expected behavior

_No response_

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines

### PR DESCRIPTION
**Pull request by qalisander**
It seems that reference types from WASM are not supported by `wasm-parser` crate (https://github.com/rustwasm/wasm-bindgen/issues/4211).
It makes us pin to the recent nightly toolchain version that works, and contribution experience gets quite convoluted.
Hopefully there is an option to disable `reference-types` with a flag: `-C target-cpu=mvp` for `wasm32-unknown-unknown` target.

Resolves #374

Single source of rust toolchain from `rust-toolchain.toml` added for ci pipelines (actions-rust-lang/setup-rust-toolchain@v1 gh action used for that).

Resolves #294

### CODE REVIEW

**Review by bidzyyys — APPROVED** [review]
Good job @qalisander, would be great if you can handle also https://github.com/OpenZeppelin/rust-contracts-stylus/issues/294 in this PR.

File: scripts/e2e-tests.sh [hunk 1]
```diff
@@ -5,10 +5,12 @@ MYDIR=$(realpath "$(dirname "$0")")
 cd "$MYDIR"
 cd ..
 
-NIGHTLY_TOOLCHAIN=${NIGHTLY_TOOLCHAIN:-nightly}
-cargo +"$NIGHTLY_TOOLCHAIN" build --release --target wasm32-unknown-unknown -Z build-std=std,panic_abort -Z build-std-features=panic_immediate_abort
+# We should use stable here once nitro-testnode is updated and the contracts fit
+# the size limit.
+RUSTUP_TOOLCHAIN=${RUSTUP_TOOLCHAIN:-nightly}
+
+cargo build --release --target wasm32-unknown-unknown -Z build-std=std,panic_abort -Z build-std-features=panic_immediate_abort
```
[the remark this answers is not in the document]
Comment (qalisander) [reply scripts/e2e-tests.sh:12]: Those are nightly compiler optimization flags. As I remember these flags been recommended for wasm size optimization.
I haven't tried to experiment with nightly flags further, since wasm size is fine for us.

File: .github/workflows/check-wasm.yml [hunk 2]
```diff
@@ -19,20 +19,13 @@ jobs:
...
-      - name: set up rust
-        uses: dtolnay/rust-toolchain@master
-        id: toolchain
+      - name: Install rust
+        uses: actions-rust-lang/setup-rust-toolchain@v1
         with:
-          target: wasm32-unknown-unknown
-          components: rust-src
-          toolchain: nightly-2024-01-01
+          rustflags: ""
```
Comment (qalisander) [inline .github/workflows/check-wasm.yml:25]: Alas we should write 'rustflags: ""` everywhere. Otherwise our optimization rust flags will be replaced by `-D warnings`. Strange behavior of this action tbh

File: contracts/src/token/erc721/mod.rs [hunk 3]
```diff
@@ -160,25 +160,29 @@ impl MethodError for Error {
...
 
-sol_interface! {
-    /// [`Erc721`] token receiver interface.
-    ///
-    /// Interface for any contract that wants to support `safe_transfers`
-    /// from [`Erc721`] asset contracts.
-    interface IERC721Receiver {
-        /// Whenever an [`Erc721`] `token_id` token is transferred
-        /// to this contract via [`Erc721::safe_transfer_from`].
+pub use receiver::*;
```
Comment (qalisander) [inline contracts/src/token/erc721/mod.rs:163]: I think we can change it back. But this hack eliminates few last warnings of rust compiler. Wdt?

File: rust-toolchain.toml [hunk 4]
```diff
@@ -0,0 +1,6 @@
+[toolchain]
+# We should use stable here once nitro-testnode is updated and the contracts fit
```
Comment (bidzyyys) [inline rust-toolchain.toml:2]: @qalisander should we add a GH issue for this?

File: contracts/src/token/erc721/mod.rs (hunk 3 above)
Comment (bidzyyys) [reply contracts/src/token/erc721/mod.rs:163]: I am okay with this.
Nit: As you are introducing a new mod I would move it to another (new) file.

File: .github/workflows/check.yml [hunk 5]
```diff
@@ -55,12 +59,15 @@ jobs:
       - uses: actions/checkout@v4
         with:
           submodules: true
-      - name: Install ${{ matrix.toolchain }}
-        uses: dtolnay/rust-toolchain@master
+
+      - name: Install rust ${{ matrix.toolchain }}
```
Comment (bidzyyys) [inline .github/workflows/check.yml:63]:
```suggestion
      - name: Install ${{ matrix.toolchain }}
```

**Review by bidzyyys — APPROVED** [review]
I like it, left small comments.

File: contracts/src/token/erc721/mod.rs (hunk 3 above)
Comment (bidzyyys) [reply contracts/src/token/erc721/mod.rs:163]: Nit: Can we have just `pub use receiver::IERC721Receiver`?

File: .github/workflows/check.yml (hunk 5 above)
Comment (qalisander) [reply .github/workflows/check.yml:63]: I've changed name on purpose. It looks like that in ci logs currently:
image

Comment (bidzyyys) [reply .github/workflows/check.yml:63]: Fair enough, thanks!

File: rust-toolchain.toml (hunk 4 above)
Comment (qalisander) [reply rust-toolchain.toml:2]: We already have [it](https://github.com/OpenZeppelin/rust-contracts-stylus/issues/129). Duplicated it in comment.

**Review by ggonzalez94 — APPROVED** [review]
LGTM!
