### PR TITLE
fix(L-02): Inconsistent Implementations in ERC-721 Extension #331

### LINKED ISSUE #312: [Audit]: L-02 Inconsistent Implementations in ERC-721 Extension
### What is the feature you would like to see?

The Stylus library ERC-721 extensions are not consistent with the respective functionality of the Solidity library.
These inconsistencies were identified:
• In the uri_storage extension, the token_uri() function directly returns the value from storage but omits key checks:
◦ It does not verify whether the token exists, which is handled in the Solidity implementation.
◦ It does not handle base URI concatenation like the Solidity version. Instead, it directly retrieves and returns the stored token URI without constructing the full URI.
• There is a mismatch in the implementation of ERC721Metadata :
◦ The Rust implementation exposes the base_uri function. In the Solidity version, URIs are only accessible by token ID when the token exists. Not exposing
baseURI is generally advisable, as revealing it prematurely can leak sensitive NFT data before minting. This can enable advanced users to time their minting to acquire more desirable NFTs.
◦ The Rust version lacks the tokenURI function by default, which may cause integration issues.
Consider aligning these implementations with the Solidity library to ensure consistency and mitigate potential risks.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines

### PR DESCRIPTION
**Pull request by bidzyyys**
Resolves #312

### CODE REVIEW

File: contracts/src/token/erc721/extensions/metadata.rs [hunk 1]
```diff
@@ -53,8 +49,57 @@ impl IErc721Metadata for Erc721Metadata {
     fn symbol(&self) -> String {
         self._metadata.symbol()
     }
+}
 
-    fn base_uri(&self) -> String {
```
Comment (qalisander) [inline contracts/src/token/erc721/extensions/metadata.rs:57]: In this case `#[interface_id]` won't be that helpful. Because methods inside `IErc721Metadata` trait are not same as in solidity (`token_uri` is missing). So computed interface id will be different..

Comment (ggonzalez94) [reply contracts/src/token/erc721/extensions/metadata.rs:57]: If this is the only thing preventing this PR I would say we don't expose `#[interface_id]` for the metadata extension(since I don't think it is part of the EIP itself).
One thing we should do is add in the Anotra docs or at the top of the contract that people should expose `token_uri` manually(I know it is on the internal function description, but still)

**Review by ggonzalez94 — COMMENTED** [review]
Looks good overall, I like using the `impl` as a parameter to the function(keeps things more clean). Let's finalize the discussion around `ERC165` support and if we need to add a note to the docs

**Review by ggonzalez94 — APPROVED** [review]
LGTM

**Review by qalisander — APPROVED** [review]
LGTM
